name: Build and release

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.x
      - name: Set package.json version
        uses: decentraland/oddish-action@master
        with:
          deterministic-snapshot: true
          only-update-versions: true
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_PATH: 'src'
          VITE_SEGMENT_DEV_API_KEY: ${{ secrets.SEGMENT_DEV_API_KEY }}
          VITE_SEGMENT_PRD_API_KEY: ${{ secrets.SEGMENT_PRD_API_KEY }}
      - name: Publish
        uses: decentraland/oddish-action@master
        with:
          cwd: './dist'
          deterministic-snapshot: true
          registry-url: 'https://registry.npmjs.org'
          access: public
          gitlab-token: ${{ secrets.GITLAB_CDN_DEPLOYER_TOKEN }}
          gitlab-pipeline-url: ${{ secrets.GITLAB_CDN_DEPLOYER_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
